spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # не создаём автоматически, используем schema.sql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  sql:
    init:
      mode: always  # выполняет schema.sql и data.sql при старте
      platform: postgres

  redis:
   host: localhost
   port: 6379
   timeout: 2000ms
   lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 минут в миллисекундах
      cache-null-values: false

app:
  data-generator:
    enabled: false
    mode: ADD           # ADD, REPLACE, SKIP_IF_EXISTS
    user-count: 200

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000  # 24 часа в миллисекундах

server:
  port: 8080
